spring:
  application:
    name: "eurekaserver"
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceURL:
      defaultZone: http://sathish:pass@localhost:8070/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"
